import Foundation
import UIKit

/// Builds a simple one-page monthly summary PDF for Penny Pro share/export.
enum MonthlySummaryPDFService {
    struct Input {
        var monthLabel: String
        var currencyCode: String
        var displayName: String
        var income: Decimal
        var spent: Decimal
        var billsMonthly: Decimal
        var safeToSpend: Decimal
        var categoryLines: [(name: String, spent: Decimal, budgeted: Decimal)]
        var billLines: [(name: String, amount: Decimal, paid: Bool)]
    }

    enum ExportError: Error, LocalizedError {
        case writeFailed

        var errorDescription: String? {
            "Penny couldn’t write the PDF file."
        }
    }

    static func exportFile(input: Input) throws -> URL {
        let page = CGRect(x: 0, y: 0, width: 612, height: 792) // US Letter
        let renderer = UIGraphicsPDFRenderer(bounds: page)
        let data = renderer.pdfData { context in
            context.beginPage()
            let margin: CGFloat = 48
            var y: CGFloat = margin

            func draw(_ text: String, font: UIFont, color: UIColor = .black, maxWidth: CGFloat? = nil) {
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: color
                ]
                let width = maxWidth ?? (page.width - margin * 2)
                let rect = CGRect(x: margin, y: y, width: width, height: 800)
                (text as NSString).draw(with: rect, options: [.usesLineFragmentOrigin], attributes: attrs, context: nil)
                let size = (text as NSString).boundingRect(
                    with: CGSize(width: width, height: 800),
                    options: [.usesLineFragmentOrigin],
                    attributes: attrs,
                    context: nil
                ).size
                y += size.height + 6
            }

            draw("My Penny", font: .systemFont(ofSize: 22, weight: .bold))
            draw("Monthly summary · \(input.monthLabel)", font: .systemFont(ofSize: 14, weight: .medium), color: .darkGray)
            if !input.displayName.isEmpty {
                draw("Prepared for \(input.displayName)", font: .systemFont(ofSize: 12), color: .gray)
            }
            y += 8
            draw("Estimates from your entries — not financial advice.", font: .italicSystemFont(ofSize: 10), color: .gray)
            y += 12

            draw("Overview", font: .systemFont(ofSize: 16, weight: .semibold))
            draw("Income: \(MoneyFormatters.string(from: input.income, currencyCode: input.currencyCode))", font: .systemFont(ofSize: 12))
            draw("Spent: \(MoneyFormatters.string(from: input.spent, currencyCode: input.currencyCode))", font: .systemFont(ofSize: 12))
            draw("Bills (monthly equiv.): \(MoneyFormatters.string(from: input.billsMonthly, currencyCode: input.currencyCode))", font: .systemFont(ofSize: 12))
            draw("Safe to Spend*: \(MoneyFormatters.string(from: input.safeToSpend, currencyCode: input.currencyCode))", font: .systemFont(ofSize: 12, weight: .semibold))
            y += 10

            if !input.categoryLines.isEmpty {
                draw("Categories", font: .systemFont(ofSize: 16, weight: .semibold))
                for line in input.categoryLines.prefix(12) {
                    let spent = MoneyFormatters.string(from: line.spent, currencyCode: input.currencyCode)
                    let budget = MoneyFormatters.string(from: line.budgeted, currencyCode: input.currencyCode)
                    draw("• \(line.name): \(spent) of \(budget)", font: .systemFont(ofSize: 11))
                }
                y += 8
            }

            if !input.billLines.isEmpty {
                draw("Bills", font: .systemFont(ofSize: 16, weight: .semibold))
                for line in input.billLines.prefix(16) {
                    let amount = MoneyFormatters.string(from: line.amount, currencyCode: input.currencyCode)
                    let status = line.paid ? "Paid" : "Unpaid"
                    draw("• \(line.name): \(amount) · \(status)", font: .systemFont(ofSize: 11))
                }
            }

            y = max(y, page.height - 64)
            draw("Generated by My Penny · on-device only", font: .systemFont(ofSize: 9), color: .gray)
        }

        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "yyyyMMdd"
        let name = "penny-summary-\(formatter.string(from: Date())).pdf"
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(name)
        do {
            try data.write(to: url, options: .atomic)
            return url
        } catch {
            throw ExportError.writeFailed
        }
    }
}
